# Use the official Python image as the base
FROM python:3.12-slim

# Set environment variables to prevent Python from buffering stdout/stderr
# ENV PYTHONUNBUFFERED=1 \
#     PIP_NO_CACHE_DIR=1 \
#     STREAMLIT_HOME="/app"

# Set the working directory in the container
WORKDIR /app

# Copy the entire Streamlit app into the container
COPY ./app/backend /app/backend
COPY ./app/data /app/data


# Install dependencies
RUN pip install --upgrade pip && \
    pip install -r backend/requirements.txt


# Expose the default Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["fastapi", "run", "/app/backend/fast_api.py"]
