# .github/workflows/keep_alive.yml
name: Keep Streamlit App Awake
on:
  workflow_dispatch:    # erlaubt “Run workflow” manuell in der UI
  schedule:
    - cron: '*/20 * * * *'  # alle 15 Minuten
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -m 10 -so /dev/null https://geomar-dashboard-v04.streamlit.app/
